# Generated by Django 4.2.7 on 2023-11-17 15:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Create_Date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='Create_Time',
            field=models.TimeField(auto_created=True, default=datetime.datetime(2023, 11, 17, 15, 30, 52, 693008, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
