# Generated by Django 4.2.7 on 2023-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todo_create_date_todo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Create_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Create_Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
